version: "3.8"
services:
  shopping-cart-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      PORT: "8080"
      DATABASE_URL: "mongodb://mongodb:27017/shopping_cart_db?retryWrites=true&w=majority"
      DATABASE_NAME: "shopping_cart_db"
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - 27017