version: "3.8"
services:
  sello-frontend:
    image: prodigy4440/sello-frontend:v1
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: "http://sello-backend:8080"
    depends_on:
      - sello-backend
  sello-backend:
    image: prodigy4440/sello-backend:v1
    ports:
      - "8080:8080"
    environment:
      PORT: "8080"
      DATABASE_URL: "mongodb://mongodb-service:27017/sello_db?retryWrites=true&w=majority"
      DATABASE_NAME: "sello_db"
    depends_on:
      - mongodb-service
  mongodb-service:
    image: mongo:latest
    ports:
      - 27017